language: android

jdk: 
  - oraclejdk8

# Install Dependencies
before_install:
    - cd ..
    - git clone --depth=50 --branch=master https://github.com/midhunhk/ae-apps-library.git midhunhk/AeAppsLib
    - cd midhunhk/trip-o-meter

# Android settings
android:
  components:
    - tools
    # Same version as specified in build.gradle
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
  licenses:
    - '.+'
     
# Run before runnig the build script
before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-bin.zip
    - unzip gradle-3.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH
  
# Licenses to be accepted
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
