language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.1
    
    # The SDK version used to compile your project
    - android-25
before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
    - unzip gradle-3.3-all.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH
