language: android
jdk: 
  - oraclejdk8
  
android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    
  licenses:
    - '.+'
    
before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
    - unzip gradle-3.3-all.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH
    
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
