version: 2

    jobs:
      build:
        docker:
          - image: circleci/openjdk:8-jdk
           
          working_directory: ~/repo

          environment:
            ANDROID_HOME: /usr/local/android-sdk-linux
            JVM_OPTS: -Xmx3200m
            TERM: dumb

         dependencies:
           pre:
             - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.1,android-23,extra-google-m2repository,extra-google-google_play_services,extra-android-support,extra-libs/android-support-v7-cardview.jar,extra-libraryForFloatingButton,extra-libs/engine.io-client-0.5.0.jar,extra-libs/httpmime-4.2.5.jar,extra-libs/okhttp-2.3.0.jar,extra-libs/okhttp-ws-2.3.0.jar,extra-libs/okio-1.3.0.jar,extra-libs/socket.io-client-0.5.0.jar,extra-com.crashlytics.sdk.android:crashlytics:2.5.5@aar
             - chmod +x gradlew
             - ANDROID_HOME = /usr/local/android-sdk-linux ./gradlew dependencies

        steps:
          - checkout
          - run: gradle dependencies    
          - run: gradle test
